### PR TITLE
Drop tin

### PR DESCRIPTION
**Pull request by mgl512**
It's in minetest_game now.

This commits removes references to moreores tin in the code and its textures files. Users who had moreores tin in their game are left to write the proper aliases themselves.

### CODE REVIEW

**Comment by Thomas--S** [comment]
I think that #18 will be slightly more convenient for the users.

**Comment by mgl512** [comment]
> I think that #18 will be slightly more convenient for the users.

I agree. It's even very convenient. But I think  this one is better for moreores itself. 

Gold used to be in moreores too but you can't see any trace of it in the mod now. The code would look messy if there was some lines dedicated to the transition from moreores gold to default gold. It's the same for tin. A way to avoid transition code that you will have to remove is to never write it. That's why I submitted this PR.

**Comment by Thomas--S** [comment]
IMHO, I think we should have this backwards compatibility code for about two minetest releases, then it can be safely removed.

**Comment by mgl512** [comment]
Old servers will want to keep the aliases forever I think, not "for about two minetest releases". It  only delays the time when they will have to write them in a custom mod.

**Comment by Desour** [comment]
If minetest_game takes more and more of the ores that are/were in moreores, this mod will end in alias code only.

**Comment by Calinou** [comment]
This one is likely to cause problems for players on stable versions, as tin was added to minetest_game after the 0.4.15 release. This will be especially problematic if these players use other mods that depend on More Ores' tin, such as Technic.

I think I'm more in favor of https://github.com/minetest-mods/moreores/pull/18.

**Comment by Calinou** [comment]
Deprecated in favor of https://github.com/minetest-mods/moreores/pull/18, which was merged.

**Pull request closed without merging**
